# Generated by Django 2.2 on 2019-04-25 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diver',
            name='first_name',
            field=models.CharField(default='Angelique', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diver',
            name='last_name',
            field=models.CharField(default='Nehmzow', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dive',
            name='diver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dives', to='logbook.Diver'),
        ),
    ]
